### ISSUE TITLE
And now what?

### ISSUE THREAD

**Issue by kklepper** [Paxa/slimerjs-docker#1]
That's great. I built the image, then

docker run -d -v /tmp:/tmp --name u1 kklepper/slimerjs:alpine ash

and it exits immediately. What now? How can I deal with it? 

I have experience with phantomjs and use https://github.com/joergpatz/docker-phantomjs 

Any hints to get me going?

**Comment by Paxa** [comment]
I run it as
```sh
docker run -it -v /tmp:/tmp --name u1 evpavel/slimerjs-alpine ash
```
and it works
```
% docker run -it -v /tmp:/tmp --name u1 evpavel/slimerjs-alpine ash
/ # ls -lah
total 56
drwxr-xr-x   38 root     root        4.0K Mar  5 15:36 .
drwxr-xr-x   38 root     root        4.0K Mar  5 15:36 ..
-rwxr-xr-x    1 root     root           0 Mar  5 15:36 .dockerenv
drwxr-xr-x    2 root     root        4.0K Feb  4 15:55 bin
drwxr-xr-x    5 root     root         360 Mar  5 15:36 dev
drwxr-xr-x   24 root     root        4.0K Mar  5 15:36 etc
drwxr-xr-x    2 root     root        4.0K Dec 26 21:32 home
drwxr-xr-x    6 root     root        4.0K Feb  4 15:55 lib
drwxr-xr-x    5 root     root        4.0K Dec 26 21:32 media
drwxr-xr-x    2 root     root        4.0K Dec 26 21:32 mnt
dr-xr-xr-x  123 root     root           0 Mar  5 15:36 proc
drwx------    6 root     root        4.0K Mar  5 15:36 root
drwxr-xr-x    2 root     root        4.0K Dec 26 21:32 run
drwxr-xr-x    2 root     root        4.0K Feb  4 15:54 sbin
drwxr-xr-x    2 root     root        4.0K Dec 26 21:32 srv
dr-xr-xr-x   13 root     root           0 Mar  5 15:36 sys
drwxrwxrwt   22 root     root         748 Mar  5 15:28 tmp
drwxr-xr-x   14 root     root        4.0K Feb  4 15:57 usr
drwxr-xr-x   17 root     root        4.0K Feb  4 15:57 var
/ # 
```

---

`-d` will run it in background, `-i` will run interactively (like any usual process), `-t` will add `pseudo-TTY` so you can type commands in shell. Probably in your case `ash` run in background and then breaks because no TTY

---

I built this image to use it in my builds with docker, for example:

```dockerfile
FROM evpavel/slimerjs-alpine:1.0

RUN mkdir -p /srv/code
WORKDIR /srv/code
# ...
COPY . /srv/code/
CMD rake # this will run my tests
```

**Comment by kklepper** [comment]
Oh, yes, my bad, so sorry about that, wrong parameters, just calling a shortcut without thinking...

Now my question is rather to understand your example and redefine it to be able to use your container as an executable. Can you give an example?

Thanks a lot for your work and even more for your prompt reply!

**Comment by kklepper** [comment]
Wait... I guess I can work it out myself. If so, I will post the answer here.

**Comment by Paxa** [comment]
You have your javascript file that you want to run with slimerjs right?

For example:
```js
console.log("Hello from slimerjs");
slimer.exit();
```
Then you can run as:
```
docker run -it -v $(pwd):/code evpavel/slimerjs-alpine slimerjs /code/example.js
```

**Comment by kklepper** [comment]
Absolutely great! Thanks a lot. 

Have to figure out how to make screenshots. Example at /usr/local/slimerjs/examples/screenshot_server.js did not work out as expected. 

```
$ docker run -it --rm -v /tmp:/tmp --name u1 kklepper/slimerjs:alpine ash
/ # slimerjs /usr/local/slimerjs/examples/screenshot_server.js &
```
and in another terminal:

```
$ curl http://localhost:9005/screenshot?url=http://google.com
curl: (7) Failed to connect to localhost port 9005: Connection refused

```

**Comment by Paxa** [comment]
you can try add `--net host` for docker command so container can access localhost ports

**Comment by kklepper** [comment]
Great! Worked! 

    curl -v http://localhost:9005/screenshot?url=http://google.com > g.jpg

Thanks so much, Pavel!
